### Análise Exploratoria de Vendas

In [79]:
import pandas as pd
import numpy as np
from pathlib import Path

caminho = Path("../data/vendas_loja.csv")

df_vendas = pd.read_csv(caminho, encoding= 'utf-8', low_memory= False)

display(df_vendas.head(11))

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
5,LIN-000006,PED-00004,2024-02-14,CLI-0236,Marcadores Coloridos,Papelaria,1,8.90,15,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
6,LIN-000007,PED-00005,2025-10-17,CLI-0052,Marcadores Coloridos,Papelaria,1,8.90,5,Cartão de débito,Viseu,Centro,Concluído
7,LIN-000008,PED-00006,2025-06-12,CLI-0037,Mochila Executiva,Acessórios,1,51.40,0,Cartão de crédito,Sintra,Lisboa e Vale do Tejo,Concluído
8,LIN-000009,PED-00007,2024-10-01,CLI-0394,Caderno A5,Papelaria,1,6.70,10,Cartão de crédito,Beja,Alentejo,Concluído
9,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
10,LIN-000011,PED-00009,2025-07-30,CLI-0220,Organizador de Mesa,Casa e Escritório,3,14.90,5,Cartão de débito,Lagos,Algarve,Concluído

#### Inspeção dos dados
1. Número de linhas | colunas

In [80]:
display(df_vendas.shape)

(1428, 13)

2. Colunas com valores NULL: data_venda, produto, preco_unitario, regiao

In [81]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_linha             1428 non-null   str
 1   id_pedido            1428 non-null   str
 2   data_venda           1425 non-null   str
 3   cliente_id           1428 non-null   str
 4   produto              1424 non-null   str
 5   categoria            1428 non-null   str
 6   quantidade           1428 non-null   int64
 7   preco_unitario       1423 non-null   float64
 8   desconto_percentual  1428 non-null   int64
 9   forma_pagamento      1428 non-null   str
 10  cidade               1428 non-null   str
 11  regiao               1420 non-null   str
 12  status_pedido        1428 non-null   str
dtypes: float64(1), int64(2), str(10)
memory usage: 145.2 KB

3. Quantos registos estão duplicados?

In [82]:
print('Duplicatas =',df_vendas.duplicated().sum())

display(df_vendas[df_vendas.duplicated(keep=False)].sort_values('id_linha').reset_index(drop = True).head(5))

Duplicatas = 12

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
1,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000037,PED-00019,2024-03-02,CLI-0161,Teclado Mecânico,Eletrónica,1,79.90,0,Cartão de débito,Porto,Norte,Concluído
3,LIN-000037,PED-00019,2024-03-02,CLI-0161,Teclado Mecânico,Eletrónica,1,79.90,0,Cartão de débito,Porto,Norte,Concluído
4,LIN-000044,PED-00022,2024-12-09,CLI-0279,Candeeiro de Mesa,Casa e Escritório,1,27.06,15,MB WAY,Setúbal,Lisboa e Vale do Tejo,Devolvido

#### Tratamento dos dados

1. Fazer uma cópia dos dados

In [83]:
df_analise = df_vendas

display(df_analise.head(5))

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído

2. Remover NULL

In [84]:
df_analise = df_analise.dropna()

display(df_analise.head(5))

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído

3. Remover duplicatas

In [85]:
df_analise = df_analise.drop_duplicates(keep='first')

display(df_analise.head(5))

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído

Conversão de tipo

In [86]:
df_analise['data_venda'] = pd.to_datetime(df_analise['data_venda'], format='%Y-%m-%d', errors='coerce')

datas_com_erro = df_analise.loc[df_analise['data_venda'].isna()]

display(df_analise[df_analise['data_venda'].isna()])

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
254,LIN-000255,PED-00144,NaT,CLI-0336,Bolsa para Portátil,Acessórios,1,27.9,0,MB WAY,Beja,Alentejo,Concluído
927,LIN-000928,PED-00496,NaT,CLI-0348,Mochila Executiva,Acessórios,2,48.4,0,Cartão de crédito,Viseu,Centro,Concluído

Análise final

In [87]:
df_analise.info()

print('Duplicatas = ',df_analise.duplicated().sum())

<class 'pandas.DataFrame'>
Index: 1396 entries, 0 to 1415
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_linha             1396 non-null   str
 1   id_pedido            1396 non-null   str
 2   data_venda           1394 non-null   datetime64[us]
 3   cliente_id           1396 non-null   str
 4   produto              1396 non-null   str
 5   categoria            1396 non-null   str
 6   quantidade           1396 non-null   int64
 7   preco_unitario       1396 non-null   float64
 8   desconto_percentual  1396 non-null   int64
 9   forma_pagamento      1396 non-null   str
 10  cidade               1396 non-null   str
 11  regiao               1396 non-null   str
 12  status_pedido        1396 non-null   str
dtypes: datetime64[us](1), float64(1), int64(2), str(9)
memory usage: 152.7 KB
Duplicatas =  0

4. Qual foi o faturamento líquido dos pedidos concluídos?

In [88]:
df_concluidos = df_analise[df_analise['status_pedido'] == 'Concluído']

In [ ]:
df_faturamento_liquido = df_concluidos[['quantidade', 'preco_unitario', 'desconto_percentual','produto','data_venda']]

df_faturamento_liquido['Preco_bruto'] = df_faturamento_liquido['quantidade'] * df_faturamento_liquido['preco_unitario']

df_faturamento_liquido['preco_liquido'] = df_faturamento_liquido['Preco_bruto'] * (1 - df_faturamento_liquido["desconto_percentual"] / 100)

preco_liquido = df_faturamento_liquido['preco_liquido'].sum()

print(f"Faturamento líquido: R$ {preco_liquido:,.2f}")

Faturamento líquido: R$ 91,247.21

5. Qual foi o ticket médio por pedido?

In [90]:
quantidade_pedidos = df_concluidos['id_pedido'].nunique()

ticket_medio = preco_liquido / quantidade_pedidos

print(f"Ticket médio: R$ {ticket_medio:,.2f}")

Ticket médio: R$ 132.05

6. Quais produtos geraram mais receita?

In [91]:
df_produtos_mais_receita = df_faturamento_liquido[['produto','preco_liquido']].groupby('produto').sum()

df_produtos_mais_receita = df_produtos_mais_receita.sort_values(by= 'preco_liquido', ascending= False)

df_produtos_mais_receita = df_produtos_mais_receita.reset_index()

df_produtos_mais_receita = df_produtos_mais_receita.rename(columns={'preco_liquido':'receita_liquida'})

display(df_produtos_mais_receita.style.hide(axis="index").format({"preco_liquido": "R$ {:,.2f}"}))

7. Quais meses tiveram maior faturamento?

In [ ]:
df_meses_faturamento = df_concluidos['data_venda']

df_meses_faturamento = df_faturamento_liquido['preco_liquido']