### Análise Exploratoria de Vendas

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

caminho = Path("../data/vendas_loja.csv")

df_vendas = pd.read_csv(caminho, encoding= 'utf-8', low_memory= False)

display(df_vendas.head(11))

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
5,LIN-000006,PED-00004,2024-02-14,CLI-0236,Marcadores Coloridos,Papelaria,1,8.90,15,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
6,LIN-000007,PED-00005,2025-10-17,CLI-0052,Marcadores Coloridos,Papelaria,1,8.90,5,Cartão de débito,Viseu,Centro,Concluído
7,LIN-000008,PED-00006,2025-06-12,CLI-0037,Mochila Executiva,Acessórios,1,51.40,0,Cartão de crédito,Sintra,Lisboa e Vale do Tejo,Concluído
8,LIN-000009,PED-00007,2024-10-01,CLI-0394,Caderno A5,Papelaria,1,6.70,10,Cartão de crédito,Beja,Alentejo,Concluído
9,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
10,LIN-000011,PED-00009,2025-07-30,CLI-0220,Organizador de Mesa,Casa e Escritório,3,14.90,5,Cartão de débito,Lagos,Algarve,Concluído

#### Inspeção dos dados
1. Número de linhas | colunas

In [2]:
display(df_vendas.shape)

(1428, 13)

2. Colunas com valores NULL: data_venda, produto, preco_unitario, regiao

In [3]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_linha             1428 non-null   str
 1   id_pedido            1428 non-null   str
 2   data_venda           1425 non-null   str
 3   cliente_id           1428 non-null   str
 4   produto              1424 non-null   str
 5   categoria            1428 non-null   str
 6   quantidade           1428 non-null   int64
 7   preco_unitario       1423 non-null   float64
 8   desconto_percentual  1428 non-null   int64
 9   forma_pagamento      1428 non-null   str
 10  cidade               1428 non-null   str
 11  regiao               1420 non-null   str
 12  status_pedido        1428 non-null   str
dtypes: float64(1), int64(2), str(10)
memory usage: 145.2 KB

3. Quantos registos estão duplicados?

In [4]:
print('Duplicatas =',df_vendas.duplicated().sum())

display(df_vendas[df_vendas.duplicated(keep=False)].sort_values('id_linha'))

Duplicatas = 12

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
9,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
1423,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
36,LIN-000037,PED-00019,2024-03-02,CLI-0161,Teclado Mecânico,Eletrónica,1,79.90,0,Cartão de débito,Porto,Norte,Concluído
1420,LIN-000037,PED-00019,2024-03-02,CLI-0161,Teclado Mecânico,Eletrónica,1,79.90,0,Cartão de débito,Porto,Norte,Concluído
43,LIN-000044,PED-00022,2024-12-09,CLI-0279,Candeeiro de Mesa,Casa e Escritório,1,27.06,15,MB WAY,Setúbal,Lisboa e Vale do Tejo,Devolvido
1418,LIN-000044,PED-00022,2024-12-09,CLI-0279,Candeeiro de Mesa,Casa e Escritório,1,27.06,15,MB WAY,Setúbal,Lisboa e Vale do Tejo,Devolvido
268,LIN-000269,PED-00152,2024-07-18,CLI-0379,Carregador USB-C,Eletrónica,4,29.00,15,Transferência,Setúbal,Lisboa e Vale do Tejo,Concluído
1426,LIN-000269,PED-00152,2024-07-18,CLI-0379,Carregador USB-C,Eletrónica,4,29.00,15,Transferência,Setúbal,Lisboa e Vale do Tejo,Concluído
484,LIN-000485,PED-00257,2024-07-26,CLI-0251,Extensão Elétrica,Casa e Escritório,2,18.90,0,Cartão de crédito,Sintra,Lisboa e Vale do Tejo,Concluído
1416,LIN-000485,PED-00257,2024-07-26,CLI-0251,Extensão Elétrica,Casa e Escritório,2,18.90,0,Cartão de crédito,Sintra,Lisboa e Vale do Tejo,Concluído
582,LIN-000583,PED-00313,2025-05-05,CLI-0417,Candeeiro de Mesa,Casa e Escritório,3,28.74,0,Cartão de débito,Sintra,Lisboa e Vale do Tejo,Concluído
1425,LIN-000583,PED-00313,2025-05-05,CLI-0417,Candeeiro de Mesa,Casa e Escritório,3,28.74,0,Cartão de débito,Sintra,Lisboa e Vale do Tejo,Concluído
583,LIN-000584,PED-00313,2025-05-05,CLI-0417,Caderno A5,Papelaria,2,6.50,0,Cartão de débito,Sintra,Lisboa e Vale do Tejo,Concluído
1419,LIN-000584,PED-00313,2025-05-05,CLI-0417,Caderno A5,Papelaria,2,6.50,0,Cartão de débito,Sintra,Lisboa e Vale do Tejo,Concluído
1427,LIN-000825,PED-00438,2025-05-10,CLI-0363,Almofada Ergonómica,Casa e Escritório,3,32.90,10,Cartão de crédito,Funchal,Ilhas,Concluído
824,LIN-000825,PED-00438,2025-05-10,CLI-0363,Almofada Ergonómica,Casa e Escritório,3,32.90,10,Cartão de crédito,Funchal,Ilhas,Concluído
945,LIN-000946,PED-00504,2025-05-17,CLI-0304,Carregador USB-C,Eletrónica,1,29.90,0,MB WAY,Porto,Norte,Concluído
1424,LIN-000946,PED-00504,2025-05-17,CLI-0304,Carregador USB-C,Eletrónica,1,29.90,0,MB WAY,Porto,Norte,Concluído
1179,LIN-001180,PED-00637,2024-07-15,CLI-0376,Coluna Bluetooth,Eletrónica,2,69.90,0,Cartão de crédito,Aveiro,Centro,Concluído
1422,LIN-001180,PED-00637,2024-07-15,CLI-0376,Coluna Bluetooth,Eletrónica,2,69.90,0,Cartão de crédito,Aveiro,Centro,Concluído
1180,LIN-001181,PED-00637,2024-07-15,CLI-0376,Extensão Elétrica,Casa e Escritório,1,18.90,0,Cartão de crédito,Aveiro,Centro,Concluído
1417,LIN-001181,PED-00637,2024-07-15,CLI-0376,Extensão Elétrica,Casa e Escritório,1,18.90,0,Cartão de crédito,Aveiro,Centro,Concluído
1421,LIN-001319,PED-00710,2025-05-02,CLI-0007,Agenda Semanal,Papelaria,1,12.90,5,Cartão de crédito,Portalegre,Alentejo,Concluído
1318,LIN-001319,PED-00710,2025-05-02,CLI-0007,Agenda Semanal,Papelaria,1,12.90,5,Cartão de crédito,Portalegre,Alentejo,Concluído

#### Tratamento dos dados

1. Fazer uma cópia dos dados

In [5]:
df_temp = df_vendas

display(df_temp.head(11))

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
5,LIN-000006,PED-00004,2024-02-14,CLI-0236,Marcadores Coloridos,Papelaria,1,8.90,15,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
6,LIN-000007,PED-00005,2025-10-17,CLI-0052,Marcadores Coloridos,Papelaria,1,8.90,5,Cartão de débito,Viseu,Centro,Concluído
7,LIN-000008,PED-00006,2025-06-12,CLI-0037,Mochila Executiva,Acessórios,1,51.40,0,Cartão de crédito,Sintra,Lisboa e Vale do Tejo,Concluído
8,LIN-000009,PED-00007,2024-10-01,CLI-0394,Caderno A5,Papelaria,1,6.70,10,Cartão de crédito,Beja,Alentejo,Concluído
9,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
10,LIN-000011,PED-00009,2025-07-30,CLI-0220,Organizador de Mesa,Casa e Escritório,3,14.90,5,Cartão de débito,Lagos,Algarve,Concluído

2. Remover NULL

In [6]:
df_temp = df_temp.dropna()

display(df_temp)

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
1424,LIN-000946,PED-00504,2025-05-17,CLI-0304,Carregador USB-C,Eletrónica,1,29.90,0,MB WAY,Porto,Norte,Concluído
1425,LIN-000583,PED-00313,2025-05-05,CLI-0417,Candeeiro de Mesa,Casa e Escritório,3,28.74,0,Cartão de débito,Sintra,Lisboa e Vale do Tejo,Concluído
1426,LIN-000269,PED-00152,2024-07-18,CLI-0379,Carregador USB-C,Eletrónica,4,29.00,15,Transferência,Setúbal,Lisboa e Vale do Tejo,Concluído
1427,LIN-000825,PED-00438,2025-05-10,CLI-0363,Almofada Ergonómica,Casa e Escritório,3,32.90,10,Cartão de crédito,Funchal,Ilhas,Concluído

3. Remover duplicatas

In [7]:
df_temp = df_temp.drop_duplicates(keep='first')

display(df_temp)

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,LIN-001412,PED-00758,2025-04-29,CLI-0311,Garrafa Térmica,Acessórios,1,22.56,10,Cartão de crédito,Viseu,Centro,Concluído
1412,LIN-001413,PED-00758,2025-04-29,CLI-0311,Carregador USB-C,Eletrónica,2,30.80,0,Cartão de crédito,Viseu,Centro,Concluído
1413,LIN-001414,PED-00759,2024-02-01,CLI-0093,Hub USB-C,Eletrónica,2,44.90,0,Cartão de débito,Faro,Algarve,Concluído
1414,LIN-001415,PED-00760,2024-09-24,CLI-0005,Agenda Semanal,Papelaria,2,12.90,0,Cartão de crédito,Aveiro,Centro,Concluído
1415,LIN-001416,PED-00760,2024-09-24,CLI-0005,Coluna Bluetooth,Eletrónica,1,69.90,0,Cartão de crédito,Aveiro,Centro,Concluído

Conversão de tipo

In [8]:
df_temp['data_venda'] = pd.to_datetime(df_temp['data_venda'], format='%Y-%m-%d', errors='coerce')

datas_com_erro = df_temp.loc[df_temp['data_venda'].isna()]

display(df_temp[df_temp['data_venda'].isna()])

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
254,LIN-000255,PED-00144,NaT,CLI-0336,Bolsa para Portátil,Acessórios,1,27.9,0,MB WAY,Beja,Alentejo,Concluído
927,LIN-000928,PED-00496,NaT,CLI-0348,Mochila Executiva,Acessórios,2,48.4,0,Cartão de crédito,Viseu,Centro,Concluído

Análise final

In [9]:
df_temp.info()

print('Duplicatas = ',df_temp.duplicated().sum())

<class 'pandas.DataFrame'>
Index: 1396 entries, 0 to 1415
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_linha             1396 non-null   str
 1   id_pedido            1396 non-null   str
 2   data_venda           1394 non-null   datetime64[us]
 3   cliente_id           1396 non-null   str
 4   produto              1396 non-null   str
 5   categoria            1396 non-null   str
 6   quantidade           1396 non-null   int64
 7   preco_unitario       1396 non-null   float64
 8   desconto_percentual  1396 non-null   int64
 9   forma_pagamento      1396 non-null   str
 10  cidade               1396 non-null   str
 11  regiao               1396 non-null   str
 12  status_pedido        1396 non-null   str
dtypes: datetime64[us](1), float64(1), int64(2), str(9)
memory usage: 152.7 KB
Duplicatas =  0

In [10]:
display(df_vendas)

,id_linha,id_pedido,data_venda,cliente_id,produto,categoria,quantidade,preco_unitario,desconto_percentual,forma_pagamento,cidade,regiao,status_pedido
0,LIN-000001,PED-00001,2025-05-11,CLI-0013,Candeeiro de Mesa,Casa e Escritório,1,27.90,0,Cartão de crédito,Évora,Alentejo,Concluído
1,LIN-000002,PED-00002,2024-03-29,CLI-0120,Candeeiro de Mesa,Casa e Escritório,1,28.74,0,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
2,LIN-000003,PED-00002,2024-03-29,CLI-0120,Suporte para Portátil,Acessórios,3,34.90,5,Cartão de crédito,Lisboa,Lisboa e Vale do Tejo,Concluído
3,LIN-000004,PED-00003,2024-10-12,CLI-0080,Marcadores Coloridos,Papelaria,3,9.17,0,MB WAY,Vila Real,Norte,Concluído
4,LIN-000005,PED-00004,2024-02-14,CLI-0236,Extensão Elétrica,Casa e Escritório,2,18.33,0,Dinheiro,Lisboa,Lisboa e Vale do Tejo,Concluído
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,LIN-000010,PED-00008,2024-09-24,CLI-0336,Webcam Full HD,Eletrónica,1,56.55,0,Transferência,Lisboa,Lisboa e Vale do Tejo,Concluído
1424,LIN-000946,PED-00504,2025-05-17,CLI-0304,Carregador USB-C,Eletrónica,1,29.90,0,MB WAY,Porto,Norte,Concluído
1425,LIN-000583,PED-00313,2025-05-05,CLI-0417,Candeeiro de Mesa,Casa e Escritório,3,28.74,0,Cartão de débito,Sintra,Lisboa e Vale do Tejo,Concluído
1426,LIN-000269,PED-00152,2024-07-18,CLI-0379,Carregador USB-C,Eletrónica,4,29.00,15,Transferência,Setúbal,Lisboa e Vale do Tejo,Concluído
1427,LIN-000825,PED-00438,2025-05-10,CLI-0363,Almofada Ergonómica,Casa e Escritório,3,32.90,10,Cartão de crédito,Funchal,Ilhas,Concluído